name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: app.ipa